[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.args]
API_URL = "https://phinan-finance-suite-production.up.railway.app"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
