"""Notes page - Structured note analysis.

Decompose opaque bank products to reveal actual fees, risks, and opportunity costs.
"""

import reflex as rx

from ...components.layout import main_layout
from ...state.user_context import UserContextState
from ..portfolio.state import PortfolioState
from .state import NoteState

def upload_zone() -> rx.Component:
    """File upload zone."""
    return rx.vstack(
        rx.upload(
            rx.vstack(
                rx.icon("file-up", size=30, color="var(--accent-9)"),
                rx.text(
                    "Drop Term Sheet PDF here",
                    weight="bold",
                    size="4",
                ),
                rx.text(
                    "Supports typical Autocallable/Reverse Convertible term sheets",
                    size="2",
                    color_scheme="gray",
                ),
                spacing="2",
                align="center",
            ),
            id="note_upload",
            multiple=False,
            accept={"application/pdf": [".pdf"]},
            max_files=1,
            border="2px dashed var(--accent-a6)",
            background="var(--accent-a2)",
            padding="2em",
            border_radius="1em",
            width="100%",
            height="200px",
            class_name="shark-hover",
        ),
        rx.cond(
            NoteState.is_uploading,
            rx.vstack(
                rx.text(NoteState.parsing_status, size="2"),
                rx.progress(value=NoteState.upload_progress, width="100%"),
                spacing="2",
                width="100%",
            ),
        ),
        rx.button(
            "Analyze Note",
            on_click=NoteState.handle_upload(rx.upload_files(upload_id="note_upload")),
            loading=NoteState.is_uploading,
            disabled=NoteState.is_uploading,
            width="100%",
        ),
        rx.cond(
            NoteState.error_message != "",
            rx.callout(
                NoteState.error_message,
                icon="alert-triangle",
                color_scheme="red",
                width="100%",
            ),
        ),
        spacing="4",
        width="100%",
    )

def valuation_card() -> rx.Component:
    """Display valuation results."""
    return rx.card(
        rx.vstack(
            rx.hstack(
                rx.heading("Valuation Analysis", size="4"),
                rx.spacer(),
                rx.badge(
                    "Generated by Phinan AI",
                    color_scheme="blue",
                    variant="soft",
                ),
                width="100%",
            ),
            rx.divider(),
            rx.grid(
                rx.vstack(
                    rx.text("Bond Floor", size="2", color_scheme="gray"),
                    rx.heading(NoteState.bond_floor_label, size="5"),
                    rx.text("PV of Principal + Coupons", size="1", color_scheme="gray"),
                    align="center",
                ),
                rx.vstack(
                    rx.text("Option Risk", size="2", color_scheme="gray"),
                    rx.heading(
                        NoteState.option_value_display,
                        size="5",
                        color_scheme="red",
                    ),
                    rx.text("Short Barrier Put Value", size="1", color_scheme="gray"),
                    align="center",
                ),
                rx.vstack(
                    rx.text("Fair Value", size="2", color_scheme="gray"),
                    rx.heading(
                        NoteState.fair_value_display,
                        size="5",
                        color_scheme="blue",
                    ),
                    rx.text("Theoretical Price", size="1", color_scheme="gray"),
                    align="center",
                ),
                rx.vstack(
                    rx.text("Implied Fee", size="2", color_scheme="gray"),
                    rx.heading(
                        NoteState.implied_fee_display,
                        size="5",
                        color_scheme=NoteState.implied_fee_color,
                    ),
                    rx.text("Instant P&L Loss", size="1", color_scheme="gray"),
                    align="center",
                ),
                columns=rx.breakpoints({"0px": "2", "768px": "4"}),
                width="100%",
                spacing="4",
            ),
            spacing="4",
            width="100%",
        ),
        width="100%",
    )

def note_details_card() -> rx.Component:
    """Display extracted note details."""
    return rx.card(
        rx.vstack(
            rx.heading("Product Key Features", size="4"),
            rx.divider(),
            rx.data_list.root(
                rx.data_list.item(
                    rx.data_list.label("Issuer"),
                    rx.data_list.value(NoteState.note_issuer),
                ),
                rx.data_list.item(
                    rx.data_list.label("Underlying"),
                    rx.data_list.value(NoteState.underlying_tickers_display),
                ),
                 rx.data_list.item(
                    rx.data_list.label("Strike"),
                    rx.data_list.value(NoteState.note_strike),
                ),
                 rx.data_list.item(
                    rx.data_list.label("Barrier"),
                    rx.data_list.value(NoteState.note_barrier),
                ),
                rx.data_list.item(
                    rx.data_list.label("Recieves Coupon"),
                    rx.data_list.value(NoteState.note_coupon),
                ),
                rx.data_list.item(
                    rx.data_list.label("Autocall Trigger"),
                    rx.data_list.value(NoteState.note_autocall),
                ),
            ),
            spacing="4",
            width="100%",
        ),
        width="100%",
    )

def notes_content() -> rx.Component:
    """Notes page content."""
    return rx.vstack(
        rx.heading("Structured Notes Analyzer", size="6"),
        rx.text(
            "Decompose opaque bank products to reveal actual fees, risks, and opportunity costs.",
            size="2",
            color_scheme="gray",
        ),
        rx.divider(),
        
        # Upload Section (Always visible if no results, otherwise collapsed or side-by-side?)
        # Let's keep it simple: Upload top, results below.
        rx.cond(
            ~NoteState.has_results,
            upload_zone(),
            rx.vstack(
                rx.hstack(
                    rx.heading(NoteState.note_summary, size="5"),
                    rx.spacer(),
                    rx.button("Analyze Another", variant="outline", on_click=NoteState.clear_analysis),
                    width="100%",
                ),
                valuation_card(),
                note_details_card(),
                spacing="4",
                width="100%",
            ),
        ),
        
        spacing="4",
        width="100%",
        max_width="800px",
    )


@rx.page(
    route="/notes",
    title="Notes | Phinan Finance Suite",
    on_load=[UserContextState.load_context, PortfolioState.load_positions],
)
def notes_page() -> rx.Component:
    """Notes page."""
    return main_layout(notes_content())
