"""AI narrative ("Phin's Take") card for the Notes module."""

import reflex as rx

from ....components.ui import synthesis_card
from ..state import NotesState


def narrative_card() -> rx.Component:
    """Plain-language explanation generated from the computed numbers."""
    return rx.cond(
        NotesState.narrative != "",
        synthesis_card(
            rx.vstack(
                rx.hstack(
                    rx.icon("sparkles", size=18, color="var(--purple-9)"),
                    rx.heading("Phin's Take", size="4"),
                    rx.spacer(),
                    rx.badge("Generated by Phinan AI", variant="soft", size="1"),
                    width="100%",
                    align="center",
                ),
                rx.divider(),
                rx.markdown(NotesState.narrative),
                rx.text(
                    "Narrative is generated from the simulation numbers above; "
                    "it is an explanation, not advice.",
                    size="1",
                    color="var(--pfs-text-muted)",
                ),
                spacing="3",
                width="100%",
            ),
            width="100%",
        ),
        rx.cond(
            NotesState.narrative_error != "",
            rx.callout(
                NotesState.narrative_error,
                icon="circle-alert",
                color_scheme="amber",
                size="1",
                width="100%",
            ),
            rx.fragment(),
        ),
    )
